"""Unit tests for public report rendering."""

from datetime import UTC, datetime

from contribution_radar.models import Candidate, Issue, Repository
from contribution_radar.report import render_report

GENERATED_AT = datetime(2026, 9, 16, 13, 0, tzinfo=UTC)


def test_render_report_discloses_automation_and_escapes_content() -> None:
    """Render linked candidates without allowing table-cell injection."""

    repository = Repository(
        name="owner/project",
        url="https://github.com/owner/project",
        stars=5_000,
        archived=False,
    )
    issue = Issue(
        repository=repository.name,
        number=42,
        title="Fix pipes | and\nnewlines",
        url="https://github.com/owner/project/issues/42",
        labels=("help wanted", "bug"),
        assignees=(),
        comments=1,
        created_at=GENERATED_AT,
        updated_at=GENERATED_AT,
    )

    report = render_report(
        [Candidate(repository, issue, 123.4, ("label: bug", "label: help wanted"))],
        GENERATED_AT,
        scanned_repositories=10,
    )

    assert "generated by `github-actions[bot]`" in report
    assert "[#42 Fix pipes \\| and newlines]" in report
    assert "| 123.4 |" in report
    assert "Repositories scanned: **10**" in report


def test_render_report_handles_no_candidates() -> None:
    """Explain when no candidate passes the quality filters."""

    report = render_report([], GENERATED_AT, scanned_repositories=2)

    assert "No unassigned, contribution-friendly issues" in report
    assert "No activity is posted to third-party repositories automatically." in report
