"""Markdown rendering for the public opportunity report."""

from datetime import datetime

from contribution_radar.models import Candidate


def render_report(
    candidates: list[Candidate],
    generated_at: datetime,
    scanned_repositories: int,
) -> str:
    """Render a transparent, review-gated Markdown report."""

    lines = [
        "# Open-source contribution radar",
        "",
        f"Last generated: `{generated_at.isoformat()}`",
        f"Repositories scanned: **{scanned_repositories}**",
        "",
        "> This report is generated by `github-actions[bot]`. It never opens upstream",
        "> issues or pull requests. Every contribution requires human review.",
        "",
        "## Recommended opportunities",
        "",
    ]

    if not candidates:
        lines.extend(
            [
                "No unassigned, contribution-friendly issues passed today's filters.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "| Score | Repository | Issue | Why it qualified |",
                "|---:|---|---|---|",
            ]
        )
        for candidate in candidates:
            repository = candidate.repository
            issue = candidate.issue
            reasons = ", ".join(candidate.reasons)
            lines.append(
                f"| {candidate.score:.1f} "
                f"| [{_escape(repository.name)}]({repository.url}) "
                f"| [#{issue.number} {_escape(issue.title)}]({issue.url}) "
                f"| {_escape(reasons)} |"
            )
        lines.append("")

    lines.extend(
        [
            "## Selection policy",
            "",
            "- The repository is active, public, and above its configured star threshold.",
            "- The issue is open, unassigned, and explicitly welcomes contributions.",
            "- Open pull requests claiming to close the issue are excluded.",
            "- Helpful bug or documentation labels improve ranking.",
            "- No activity is posted to third-party repositories automatically.",
            "",
            "Repository targets are maintained in "
            "[`config/repositories.json`](config/repositories.json).",
            "",
        ]
    )
    return "\n".join(lines)


def _escape(value: str) -> str:
    """Escape user-controlled text for a Markdown table cell."""

    return value.replace("\\", "\\\\").replace("|", "\\|").replace("\r", " ").replace("\n", " ")
